# /path/to/project/.cargo/config.toml
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    # (Nightly) Make the current crate share its generic instantiations
    "-Zshare-generics=y",
    "-C",
    "link-arg=-fuse-ld=/usr/bin/mold",
]

[alias]
# Documentation aliases
docs-build = "run --package mdbook -- build docs"
docs-serve = "run --package mdbook -- serve docs --open"
docs-check = "run --package mdbook -- test docs"
